platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'TicTacToe' do
  pod 'RIBs', :path => '../../../'
  pod 'SnapKit', '~> 5'
  pod 'RxCocoa', '~> 5'
end

target 'TicTacToeTests' do
    pod 'RIBs', :path => '../../../'
end
